#index:
#    path: /
#    controller: App\Controller\DefaultController::index

hello_page:
  path: /default
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: 'main.html.twig'